using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace VitalRegistrationSystem.Utilities
{
    public enum District
    {
        Achham,
        Arghakhanchi,
        Baglung,
        Baitadi,
        Bajhang,
        Bajura,
        Banke,
        Bara,
        Bardiya,
        Bhaktapur,
        Bhojpur,
        Chitwan,
        Dadeldhura,
        Dailekh,
        Dang,
        Darchula,
        Dhading,
        Dhankuta,
        Dhanusa,
        Dholkha,
        Dolpa,
        Doti,
        Gorkha,
        Gulmi,
        Humla,
        Illam,
        Jajarkot,
        Jhapa,
        Jumla,
        Kailali,
        Kalikot,
        Kanchanpur,
        Kapilvastu,
        Kaski,
        Kathmandu,
        Kavrepalanchok,
        Khotang,
        Lalitpur,
        Lamjung,
        Mahottari,
        Makwanpur,
        Manang,
        Morang,
        Mugu,
        Mustang,
        Myagdi,
        Nawalpur,
        Parasi,
        Nuwakot,
        Okhaldhunga,
        Palpa,
        Panchthar,
        Parbat,
        Parsa,
        Pyuthan,
        Ramechhap,
        Rasuwa,
        Rautahat,
        Rolpa,
        RukumEast,
        RukumWest,
        Rupandehi,
        Salyan,
        Sankhuwasabha,
        Saptari,
        Sarlahi,
        Sindhuli,
        Sindhupalchok,
        Siraha,
        Solukhumbu,
        Sunsari,
        Surkhet,
        Syangja,
        Tanahun,
        Taplejung,
        Terhathum,
        Udayapur
    }

}
