// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VitalRegistrationSystem.Data;

#nullable disable

namespace VitalRegistrationSystem.Migrations
{
    [DbContext(typeof(VRSDataContext))]
    [Migration("20230527082021_AddBirthModelToDb")]
    partial class AddBirthModelToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VitalRegistrationSystem.Models.BirthModel", b =>
                {
                    b.Property<Guid>("BirthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicantAddress")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantCitizenshipNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthRegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChildAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ChildName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FatherCitizenshipNumber")
                        .HasColumnType("text");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("GrandFathersName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotherCitizenshipNumber")
                        .HasColumnType("text");

                    b.Property<string>("MothersName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BirthId");

                    b.ToTable("Births");
                });
#pragma warning restore 612, 618
        }
    }
}
